### ISSUE TITLE
Admin user condition and template var

### ISSUE THREAD

**Issue by i00** [maykar/custom-header#101]
Please add an admin_user variable (bool) to denote if the user is admin or not.

Thanks

**Comment by i00** [comment]
> Please, be sure to read the [issues section](https://maykar.github.io/custom-header/#issues) of the docs and provide the required information. Issues that don't provide the necessary information may not get a reply and may be closed.

This is not an issue, but rather a feature request ... I read that I don't think it applies to this.  I also think that the description I provided is quite adequate for the request.

Please let me know if you want any further clarification.

**Comment by maykar** [comment]
That is just the automatic bot replying to you, unfortunately it's not smart enough to read the feature request label yet and replies that to every issue.

I will be adding this as both an exception condition and a template variable

**Comment by maykar** [comment]
This has been added or fixed in the [latest version 1.2.2](https://community.home-assistant.io/t/custom-header/155399/367). After updating be sure to check your browser's dev console (usually F12) to make sure you are running the latest version. If it doesn't display 1.2.2 you may either need to clear your cache or reinstall.
