### ISSUE TITLE
Theme doesn't stick and no logout option

### ISSUE THREAD

**Issue by xbmcnut** [maykar/custom-header#124]
Great useful add-on so thanks for developing it.

I've been the only user for many years but now that CS has evolved with exceptions and many options, I'm trying to set up CS with three new users; one each for my two family members and a generic one for tablet use.

I've come across two issues today though when attempting to set this up.

1. The icons are not visible when the users them is set to backend-selected. Changing the theme to anything else fixes the issue but as soon as you logout, the theme is restored to backend-selected and the icons disappear again. Is there a way to force a user theme with CH?
2. I only have one tab available for the family and everything else is hidden. I hide raw, CH, sidebar, help etc but although this works fine, there is now no way to logout to test another user. It'd be nice to always have a logout option visible. For now, If I enter http://ipaddressofhassio:8123/logout I get a 404 error and then I can login again.

Using 0.104.3 Hassio with CH version 1.3.2 and and HACS 0.20.9

**Comment by maykar** [comment]
1. Are the icons not visible or could it be that the selected theme has the icons and header background as the same color? If it is the ladder then you could simply change that in the theme, in [CH's styling options](https://maykar.github.io/custom-header/#styling/styling), or use [CH theme variables](https://maykar.github.io/custom-header/#styling/advanced).

2. I don't think I'd add a custom logout option as that's pretty edge case, but if you add [?disable_ch](https://maykar.github.io/custom-header/#intro/notes) to the end of the URL then you can access the logout option again. You could even get creative with templates and the `disable: ` option to make a button/etc that will restore the UI so that you can then logout. Something like:

```disable: '{ is_state("input_boolean.disable", "on") }'```

**Comment by xbmcnut** [comment]
Thanks for the prompt reply. Themes seems to now be sticking but I don't know why. Set theme is tab and left 'cards' with backend-selected and working OK now.

Agree with the logout. Never much need for that other than for setting up new users and testing views.
