### ISSUE TITLE
when i pull down the refresh the page, there's a white gap on the top

### ISSUE THREAD

**Issue by horacecar** [maykar/custom-header#144]
Hello.,when i pull down the refresh the page, there's a white gap on the top. it is very hard to say, so let us to watch the video, before when i using cch with the same config, it was look like the photo below,it is great, all the bar and icon pinned and fixed on the top.

Video below : desktop.zip
[Desktop.ZIP](https://github.com/maykar/custom-header/files/4301896/Desktop.ZIP)

![before](https://user-images.githubusercontent.com/44496483/76144879-63f14e00-60bf-11ea-8a31-a47ecfda6339.png)
Before^^^^^^^^^^^^^^^^^^^^^^^

but now i upgrate to custom-header, when i pull it to refresh all the bar and icon pull together , there are big white gap on the top don't look good.  Can we fix this ?
![after](https://user-images.githubusercontent.com/44496483/76144882-6784d500-60bf-11ea-8dbf-942bf24be305.png)

**Comment by maykar** [comment]
In order to accommodate new features and fix a ton of issues that existed in CCH, Custom Header now creates its own header and hides the default one rather than modifying the default header. Since it's not the default header element anymore I would assume that the iOS app just sees it as another element causing it to move down like the others.

Unfortunately, I don't believe this is something that I could fix and since it's a very minor thing that only happens on a page refresh it's not really a priority. I will look into it in case I'm wrong, but am going to close this one as I don't think it's possible.
