### ISSUE TITLE
Display issue with theme with a background

### ISSUE THREAD

**Issue by lispwarez** [maykar/custom-header#170]
There seems to be a blank bar at the bottom of pages as can be seen in the image below (the blank bar is just a lack of background image)
![image](https://user-images.githubusercontent.com/17847646/79577775-8d8d9400-80c5-11ea-9563-8c68b930a318.png)

This issue only shows if your theme has a background image and only shows on secondary+ Lovelace dashboards with custom-header installed. 
Disabling custom-header doesnt solve the problem.
Uninstall custom-header and problem goes away.
Problem is found on all browsers I have tried

Versions:
Home assistant: 0.108.4 (also did it in 0.107.x)
custom-header: 1.3.8
Chrome: 80
Firefox: 75
Android client: 1.8.0-144

The theme I am using can be found here [https://github.com/lispwarez/hass/blob/master/themes/midnight2.yaml](url)

**Comment by VictorWinberg** [comment]
+1

Issue again:
![image](https://user-images.githubusercontent.com/9520959/79905874-36febd80-8417-11ea-9d2e-f39b859544c0.png)

The issue arise from setting `ch-header` and `ch-footer` to `visibility: hidden` instead of `display: none`, see below.
![image](https://user-images.githubusercontent.com/9520959/79905591-c48ddd80-8416-11ea-8022-febe9e2bab76.png)

**Comment by maykar** [comment]
Much has changed recently and I cannot reproduce this in the latest version. The current version is 1.4.5. Is this still an issue?

**Comment by lispwarez** [comment]
I just completed my upgrade to 0.110.1 along with custom-header and all seems to be fine now
Thank you
