### ISSUE TITLE
Header disappears completely after entering and then exiting raw configuration mode

### ISSUE THREAD

**Issue by Villhellm** [maykar/custom-header#178]
No configuration for custom_header needs to exist for this to happen, just adding custom_header to resources causes this to happen.

Steps to recreate:
1. Enter raw configuration mode in the UI
2. Exit raw configuration mode
3. Wait up to 30 seconds, the header blinks out of existence

Refreshing the page fixes it as far as I can tell, so it's not super critical.

**Comment by maykar** [comment]
As mentioned in the [important notes](https://maykar.github.io/custom-header/#intro/notes) you must refresh after using raw config editor. This is necessary and can't/won't be fixed.

**Comment by Villhellm** [comment]
"you will need to refresh the page to restore Custom Header" this problem is present without any configuration. It's still the default header. Is there a reason you have no interest in fixing this? It's not difficult to detect when the editor closes

**Comment by maykar** [comment]
Custom Header is completely unloaded when raw config opens, so when adding a way to detect when it opens, that detection ceases to function when it does. I've tried quite a few different ways to accomplish this, but ultimately concluded that it wasn't worth the effort especially since refreshing after changes to CH config solves many other issues. Otherwise it would require not only the initial solution but also a constant check for config changes, slowing things down even more

**Comment by maykar** [comment]
Also, Custom Header with no config is not the default header. It is a header created by that looks like the default header.

**Comment by maykar** [comment]
I will look into this more though when I'm back at it. The fact that the header hides after entering raw config means that changes made during the last rewrite have solved a portion of the problem

**Comment by Villhellm** [comment]
Was unloading when the raw config was opened something you implemented or a previous function of lovelace? It doesn't appear to be that way anymore if it was a lovelace thing. My mutation observers stay active through raw edit open/close. It may have changed when they added multiple dashboards since dashboards can share resources.

**Comment by maykar** [comment]
It was a limitation of earlier versions of Custom Header/CCH, but it has been rewritten a few times since then and like you mention HA has evolved as well. I was misunderstanding the original issue as CH disappears instead of neither header existing. The mutation observer that hides the default header is obviously still functioning so this is probably something I can handle now when I get the time.

**Comment by maykar** [comment]
Finally had time to look into this a bit more. The mutation observers don't survive unfortunately. The header disappears after closing raw config because the timeout to update config every minute (for templates) triggers one last time if you spend less than it's remaining minute in the editor. So, now I'm adding a timeout loop to detect a raw config exit and will rebuild when it happens. Should be in the next release.

**Comment by maykar** [comment]
Added this to 1.4.8. Made it a pre-release as it should probably go through some testing. It was [a bit more of an undertaking](https://github.com/maykar/custom-header/commit/c3628fad4204f07dafc45208e7ee937d52dab7c0) than I had anticipated. Had to account for the fact that when in edit mode or raw config mode on the main dashboard you can move to another dashboard and when you return to it they're still active. A fair few mutation observers and timeouts were required.

**Comment by Villhellm** [comment]
When I get a chance I'll compare your mutation observer implementation with my own. It might just be different because I'm not changing the header in my plugin, but going between dashboards in/out of edit mode doesn't appear to affect my observers. I could just be dumb and missing something.
Thank you for putting in the time to fix this though! I'll install the pre-release right now

**Comment by Villhellm** [comment]
Huh, only the main dashboard keeps the editor open if you switch dashboards. That's interesting

**Comment by maykar** [comment]
A fair bit of the elements  (or their parent elements)  I need to watch for get removed/replaced when interacting with the interface, so the observers go with them. Have a few instances where I have to use and observer to add an observer to a nested object that hasn't appeared yet. I also need to wait for smaller elements to pop into existence during changes in the view before I can act on them, like waiting for a button to appear to knows the default header finished building.

Looks like most of the observers for Animated Backgrounds are high enough in the chain that it wouldn't be an issue.

Just started using it BTW, it's very cool. Adding subtle animations to Lovelace is my new favorite thing.

**Comment by Villhellm** [comment]
Ah yeah that makes sense. I guess things change when you're actively messing with header elements.
Glad you like it! There's one observer I'm not even 100% sure it does anything. Someone was requesting reload when they close/open their laptop. Apparently it worked, but I have no idea how or why
