### ISSUE TITLE
Sidebar "hamburger" menu broken?

### ISSUE THREAD

**Issue by CorneliousJD** [maykar/custom-header#199]
If you ahve the sidebar hidden the hamburger button shows up to normally expand it, but since upgrading to HA 0.110.0 or 0.110.1 the hamburger button with a hidden sidebar no longer works with customer header enabled.

**Comment by maykar** [comment]
Please provide as much info from the link bots post above.

Some additional info that would help:
* How are you hiding the sidebar, with HA settings (always hide sidebar) or with CH settings?
* What browser is this happening in, does it happen in all browsers, is this only a mobile app issue, etc?

**Comment by CorneliousJD** [comment]
> Please provide as much info from the link in the bots post above.
> 
> Some additional info that would help:
> 
> * How are you hiding the sidebar, with HA settings (always hide sidebar) or with CH settings?
> * What browser is this happening in, does it happen in all browsers, is this only a mobile app issue, etc?


Yes, hiding the sidebar in account settings built into HA. Same exact thing happens on mobile as well with custom header enabled too, either way, mobile app or force hiding the sidebar in the account settings.
![image](https://user-images.githubusercontent.com/724777/82719351-c34f0b00-9c77-11ea-8290-52c847abe09a.png)

Happens on mobile app, chrome, and fully kiosk browsers at the very least, seems to be across the board.

**Comment by maykar** [comment]
Some more things from the link in the bots post: 

* Could you share your config?
* Is this the latest version of CH 1.4.5? You can verify that it's not a caching issue by opening up your browser's dev tools to make sure it is displaying 1.4.5, While you're there you can see if dev tools displays any errors related to CH. 
* Any errors in HA logs?

I ask these things so that I can try to recreate these issues. This is the first that this has been reported and I do not see that behavior on any of my devices (including android companion app, fully kiosk, and chrome).

![hiddensidebar](https://user-images.githubusercontent.com/25127328/82719636-6b65d380-9c7a-11ea-81a8-198ec6726341.gif)

**Comment by CorneliousJD** [comment]
Ok, I'm so sorry,  I was on 1.4.4, updated and restarted HA docker container, and restarted fully kiosk and the mobile apps and everything appears good now again. I don't know if there was a fix you inadvertently incoporated in 1.4.5 but all good now, sorry for wasting time with this, but I greatly appreciate the replies :) 

Have a good one, stay safe!
