### ISSUE TITLE
High number or error entries

### ISSUE THREAD

**Issue by Pirol62** [maykar/custom-header#206]
CH Version: 1.4.7
HA Version: 109.6 on Rasp3+ Hass.io
Running HA companion App on several devices
Issue:
````
Logger: frontend.js.latest.202004272
Source: components/system_log/__init__.py:209
First occurred: 1. Juni 2020, 18:05:28 (275 occurrences)
Last logged: 8:05:03

https://i0gyzxe3ihswk7c828fvjz6uss4qm87c.ui.nabu.casa/hacsfiles/custom-header/custom-header.js:596:15315 Uncaught TypeError: Cannot read property 'setAttribute' of null
Erfolgreich gespeichert
````
The errors are definately caused by the mobile app.
I have interestingly some devices connected via duckdns. These apps do not create errors.

**Comment by maykar** [comment]
Few options. Either upgrade to the latest pre-release of HA (currently 1.4.9 ), to show pre-releases in HACS you hit reinstall on CH and turn on "show betas".

Alternatively, since the newer versions of CH are made for higher versions of HA: upgrade HA to above 0.110 or downgrade CH to a version around 1.3.8

**Comment by Pirol62** [comment]
Ok, I will update to 110.4 on Thursday.
Thanks
