### ISSUE TITLE
Update config & style on device orientation change.

### ISSUE THREAD

**Issue by nassost79** [maykar/custom-header#220]
So that we could use different config depending for example on whether a tablet is held in portrait or landscape mode.
Even better if no rebuilding or refreshing was necessary.

**Comment by maykar** [comment]
I think this would be better described as a restyling of the header on orientation switch. The rebuilding/restyling of the header is not something that is really noticed so it wouldn't be disruptive. The header already restyles on template changes, every minute, etc. Since media queries are already a condition, I think this would just come down to restyling when orientation changes.

**Comment by maykar** [comment]
Added in 1.5.8

Config and header are updated on device orientation change
