### ISSUE TITLE
CH Menu button does not work in official HA android app

### ISSUE THREAD

**Issue by jo-me** [maykar/custom-header#268]
HA 0.115.3
CH 1.8.0
Latest Android app

The custom header's "menu" button that is shown on the HA dashboard instead of the hamburger menu is not working for me when using the official HA android app.
It just does nothing. 
Workaround ist swiping in the menu from the left.
Menu button works in chrome though.

**Comment by jo-me** [comment]
I've played around with the app a bit more and I found that it is only not working on my tablet in portrait mode.

**Comment by jo-me** [comment]
I can reproduce this also in Chrome when  enabling the device toolbar in the Dev Tools and setting the screen size to 800x1200 for example.
There is no output on the dev console when I click the button, though.

**Comment by maykar** [comment]
Ah, this sounds a lot like an issue that was just fixed in the latest release. Give that a try. I was able to reproduce this on 1.8.0 using chrome dev tools as you mentioned above, but after updating to the current release 1.8.3 it works fine, but this doesn't mean that the issue would be fixed for your tablet.

So, give 1.8.3 a try and let me know if it's still an issue on your tablet. If it is, I have a pretty good idea of what is happening.

**Comment by jo-me** [comment]
You're right. After the latest update it works on the tablet. .. thanks!

Ryan Meek <notifications@github.com> schrieb am Mi., 30. Sep. 2020, 22:12:
