### ISSUE TITLE
Specific View causes bug when hidden

### ISSUE THREAD

**Issue by Alexxander0** [maykar/custom-header#75]
Hi,

[Edit] "auto" in viewname causes bug.

Custom Header Installed: 1.1.7
HomeAssistant: 0.103.5

my config:
```
custom_header:
  hide_tabs: 'alex, alexauto'
```

The bug causes the header to appear twice, normal at the top and on the bottom again:
![image](https://user-images.githubusercontent.com/26937883/71728815-6c6aa580-2e3e-11ea-8e70-cf047af9b904.png)

![image](https://user-images.githubusercontent.com/26937883/71728971-e1d67600-2e3e-11ea-8d47-dd7e4c8f29b3.png)

This only happens with this view, other views (multible) work fine

Do you need further information?

**EDIT: Found the problem: If you include "auto" in viewname, this will cause the bug. Maybe a problem by parsing the config**

**Comment by igloo15** [comment]
I also ran into this issue when using the word `touch`. Looked at the code and found that the issue has to do with just two letters `to`. If your tab contains those two letters it will not work. So _au**to**_ or _**to**uch_ were creating problems with the build range function. 

Since currently the code is keying in on the letters `to` https://github.com/maykar/custom-header/blob/7397624a047cac77e80afe23a410b7a9b5b9ffd1/src/helpers.js#L51

Most likely the best option would be to search for ` to ` with spaces on either side instead of just `to`. 

I am on Home Assistant 0.103.4, HACS 0.20.4, Custom Header 1.1.7

**Comment by Alexxander0** [comment]
Ah, thats the source of problem. I didnt find any trim function in the js code. But changing https://github.com/maykar/custom-header/blob/7397624a047cac77e80afe23a410b7a9b5b9ffd1/src/helpers.js#L52

to 

`if (string.includes(' to ')) { `

might solve the problem?

**Comment by maykar** [comment]
Yup, i just need to change the detection of includes 'to' to make sure that it is surrounded by numbers. Thanks for finding this one, will be fixed in the next release.

**Comment by maykar** [comment]
Please try the latest pre-release 1.1.9 and let me know if it helps. If using HACS you will need to "show beta" in order to see the release and install it. Thanks.

**Comment by maykar** [comment]
Should be fixed in latest release, if not please reopen.
